/opt/homebrew/Library/Homebrew/cmd/shellenv.sh: line 27: /bin/ps: Operation not permitted
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
/opt/homebrew/Library/Homebrew/cmd/shellenv.sh: line 27: /bin/ps: Operation not permitted
const STORE='balance-board-tasks-v2';
const categories=[['からだ','#35a571'],['食事','#f28a3a'],['暮らし','#3da6d8'],['ペット','#8a62d5'],['自分時間','#e96fa5']];
const defaults=[
 {id:1,category:'からだ',title:'朝のストレッチを10分する',status:'習慣',priority:'中',due:'2026-08-23',progress:80,notes:'肩と股関節を中心に。'},
 {id:2,category:'食事',title:'1週間分の献立を決めて買い出し',status:'未着手',priority:'高',due:'2026-08-24',progress:0,notes:'野菜、卵、ヨーグルト、猫用おやつ'},
 {id:3,category:'暮らし',title:'クローゼット上段の収納を見直す',status:'進行中',priority:'中',due:'2026-08-29',progress:40,notes:'季節外の服をケースへ移す。'},
 {id:4,category:'ペット',title:'トイレ砂とフードの在庫チェック',status:'未着手',priority:'高',due:'2026-08-25',progress:0,notes:''},
 {id:5,category:'自分時間',title:'読みかけの本を30ページ読む',status:'進行中',priority:'低',due:'2026-08-27',progress:55,notes:'夜はスマホを置いて読む。'},
 {id:6,category:'暮らし',title:'キッチンの換気扇を掃除する',status:'あとで',priority:'低',due:'2026-09-05',progress:0,notes:''}
];
let tasks=load(),view='list',categoryFilter='all',statusFilter='all',sort='due',query='',month=new Date();
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{const saved=JSON.parse(localStorage.getItem(STORE));return Array.isArray(saved)?saved:defaults}catch{return defaults}}
function persist(){localStorage.setItem(STORE,JSON.stringify(tasks))}
function colorOf(c){return categories.find(x=>x[0]===c)?.[1]||'#8996a8'}
function filteredTasks(){let list=tasks.filter(t=>view==='done'?t.status==='完了':t.status!=='完了');if(categoryFilter!=='all')list=list.filter(t=>t.category===categoryFilter);if(statusFilter!=='all'&&view!=='done')list=list.filter(t=>t.status===statusFilter);if(query)list=list.filter(t=>(t.title+' '+t.category+' '+(t.notes||'')).toLowerCase().includes(query));const weight={高:0,中:1,低:2};return list.sort((a,b)=>sort==='priority'?weight[a.priority]-weight[b.priority]:sort==='new'?b.id-a.id:(a.due||'9999').localeCompare(b.due||'9999'))}
function statusClass(s){return {'未着手':'status-open','進行中':'status-doing','習慣':'status-habit','あとで':'status-later','完了':'status-done'}[s]||'status-open'}
function renderStats(){const open=tasks.filter(t=>t.status!=='完了'),today=dateKey(new Date()),weekEnd=new Date();weekEnd.setDate(weekEnd.getDate()+7);const done=tasks.filter(t=>t.status==='完了').length,total=tasks.length;const data=[['今日',open.filter(t=>t.due===today).length,'#ed665f'],['進行中',open.filter(t=>t.status==='進行中').length,'#3567d6'],['7日以内',open.filter(t=>t.due>=today&&t.due<=dateKey(weekEnd)).length,'#35a571'],['達成率',total?Math.round(done/total*100)+'%':'0%','#8a62d5']];$('stats').innerHTML=data.map(([a,b,c])=>`<div class="stat" style="border-color:${c}"><small>${a}</small><b>${b}</b></div>`).join('')}
function listMarkup(){const data=filteredTasks();if(!data.length)return `<div class="empty-state"><strong>該当する予定はありません</strong><p>絞り込みを解除するか、新しい予定を追加してください。</p></div>`;const rows=data.map(t=>`<tr><td class="category"><i class="dot" style="background:${colorOf(t.category)}"></i>${esc(t.category)}</td><td class="task-title"><button onclick="openEdit(${t.id})">${esc(t.title)}</button>${t.notes?`<small class="note-preview">${esc(t.notes)}</small>`:''}</td><td><span class="badge ${statusClass(t.status)}">${t.status}</span></td><td class="${t.priority==='高'?'priority-high':''}">${t.priority}</td><td>${esc(t.due||'未定')}</td><td><div class="progress"><span class="progress-bar"><i style="width:${t.progress}%"></i></span>${t.progress}%</div></td><td><div class="row-actions"><button class="small-button" onclick="openEdit(${t.id})">編集</button><button class="small-button" onclick="quickDone(${t.id})">${t.status==='完了'?'戻す':'完了'}</button></div></td></tr>`).join('');const cards=data.map(t=>`<article class="mobile-card"><div class="mobile-card-head"><span class="category"><i class="dot" style="display:inline-block;background:${colorOf(t.category)};margin-right:6px"></i>${esc(t.category)}</span><span class="badge ${statusClass(t.status)}">${t.status}</span></div><h3>${esc(t.title)}</h3>${t.notes?`<p class="mobile-note">${esc(t.notes)}</p>`:''}<div class="mobile-card-meta"><span>期限日　${esc(t.due||'未定')}</span><span>優先度　<b class="${t.priority==='高'?'priority-high':''}">${t.priority}</b></span><span>進捗　${t.progress}%</span><span>${t.notes?'メモあり':'メモなし'}</span></div><div class="mobile-card-actions"><button class="small-button" onclick="openEdit(${t.id})">編集</button><button class="small-button" onclick="quickDone(${t.id})">${t.status==='完了'?'一覧へ戻す':'完了にする'}</button></div></article>`).join('');return `<div class="table-wrap"><table class="task-table"><thead><tr>${['カテゴリ','やること・メモ','状態','優先度','期限日','進捗','操作'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table><div class="mobile-list">${cards}</div></div>`}
function calendarMarkup(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),today=dateKey(new Date()),monthTasks=filteredTasks().filter(t=>t.due?.startsWith(`${y}-${String(m+1).padStart(2,'0')}`));let cells=Array.from({length:first},()=>'<div class="calendar-day is-out"></div>');for(let d=1;d<=last;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,events=monthTasks.filter(t=>t.due===key);cells.push(`<div class="calendar-day"><span class="day-number ${key===today?'is-today':''}">${d}</span>${events.map(t=>`<button class="calendar-event" style="border-color:${colorOf(t.category)}" onclick="openEdit(${t.id})" title="${esc(t.title)}">${esc(t.title)}</button>`).join('')}</div>`)}const agenda=monthTasks.length?monthTasks.map(t=>`<button class="agenda-item" onclick="openEdit(${t.id})"><time>${Number(t.due.slice(-2))}<small>${['日','月','火','水','木','金','土'][new Date(t.due+'T00:00:00').getDay()]}</small></time><i style="background:${colorOf(t.category)}"></i><span><b>${esc(t.title)}</b><small>${esc(t.category)} ・ 期限日 ${esc(t.due)}</small>${t.notes?`<em>${esc(t.notes)}</em>`:''}</span><strong class="badge ${statusClass(t.status)}">${t.status}</strong></button>`).join(''):`<div class="empty-state"><strong>この月の予定はありません</strong></div>`;return `<div class="calendar-head"><button onclick="moveMonth(-1)" aria-label="前月">‹</button><b>${y}年${m+1}月</b><button onclick="moveMonth(1)" aria-label="翌月">›</button></div><div class="calendar-desktop"><div class="week">${['日','月','火','水','木','金','土'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div></div><div class="calendar-agenda">${agenda}</div>`}
function render(){document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.category-button').forEach(b=>b.classList.toggle('active',b.dataset.category===categoryFilter));$('viewTitle').textContent=view==='list'?'暮らしのやること':view==='calendar'?'暮らしのカレンダー':'できたこと';$('statusFilter').disabled=view==='done';$('clearFilter').classList.toggle('hidden',categoryFilter==='all'&&statusFilter==='all'&&!query);renderStats();$('panel').innerHTML=view==='calendar'?calendarMarkup():listMarkup()}
function openModal(task){$('taskForm').reset();$('taskId').value=task?.id||'';$('taskTitle').value=task?.title||'';$('taskCategory').value=task?.category||'暮らし';$('taskStatus').value=task?.status||'未着手';$('taskPriority').value=task?.priority||'中';$('taskDue').value=task?.due||dateKey(new Date());$('taskProgress').value=task?.progress||0;$('progressOutput').value=(task?.progress||0)+'%';$('taskNotes').value=task?.notes||'';$('modalMode').textContent=task?'EDIT TASK':'NEW TASK';$('modalTitle').textContent=task?'やることを編集':'やることを追加';$('deleteButton').classList.toggle('hidden',!task);$('taskModal').classList.remove('hidden');setTimeout(()=>$('taskTitle').focus(),0)}
function closeModal(){$('taskModal').classList.add('hidden')}
window.openEdit=id=>openModal(tasks.find(t=>t.id===id));window.quickDone=id=>{tasks=tasks.map(t=>t.id===id?{...t,status:t.status==='完了'?'未着手':'完了',progress:t.status==='完了'?Math.min(t.progress,95):100}:t);persist();render();toast('状態を更新しました')};window.moveMonth=n=>{month=new Date(month.getFullYear(),month.getMonth()+n,1);render()};
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2200)}function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
$('categoryNav').innerHTML=`<button class="category-button active" data-category="all"><i class="dot" style="background:#8996a8"></i>すべて</button>`+categories.map(([c,color])=>`<button class="category-button" data-category="${c}"><i class="dot" style="background:${color}"></i>${c}</button>`).join('');$('taskCategory').innerHTML=categories.map(([c])=>`<option>${c}</option>`).join('');
document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('categoryNav').onclick=e=>{const b=e.target.closest('.category-button');if(!b)return;categoryFilter=b.dataset.category;render()};$('search').oninput=e=>{query=e.target.value.trim().toLowerCase();render()};$('statusFilter').onchange=e=>{statusFilter=e.target.value;render()};$('sort').onchange=e=>{sort=e.target.value;render()};$('clearFilter').onclick=()=>{categoryFilter='all';statusFilter='all';query='';$('search').value='';$('statusFilter').value='all';render()};[$('addButton'),$('mobileAdd')].forEach(b=>b.onclick=()=>openModal());document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);$('taskModal').onclick=e=>{if(e.target===$('taskModal'))closeModal()};$('taskProgress').oninput=e=>$('progressOutput').value=e.target.value+'%';
$('taskForm').onsubmit=e=>{e.preventDefault();const id=Number($('taskId').value),data={id:id||Date.now(),title:$('taskTitle').value.trim(),category:$('taskCategory').value,status:$('taskStatus').value,priority:$('taskPriority').value,due:$('taskDue').value,progress:Number($('taskProgress').value),notes:$('taskNotes').value.trim()};if(data.status==='完了')data.progress=100;tasks=id?tasks.map(t=>t.id===id?data:t):[data,...tasks];persist();closeModal();render();toast(id?'内容を更新しました':'一覧とカレンダーに追加しました')};$('deleteButton').onclick=()=>{const id=Number($('taskId').value);if(!id||!confirm('この予定を削除しますか？'))return;tasks=tasks.filter(t=>t.id!==id);persist();closeModal();render();toast('予定を削除しました')};
$('todayLabel').textContent=new Intl.DateTimeFormat('ja-JP',{dateStyle:'full'}).format(new Date());render();
